// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type Any byte

const (
	AnyNONE      Any = 0
	AnyFindNode  Any = 1
	AnyFindValue Any = 2
	AnyStore     Any = 3
)

var EnumNamesAny = map[Any]string{
	AnyNONE:      "NONE",
	AnyFindNode:  "FindNode",
	AnyFindValue: "FindValue",
	AnyStore:     "Store",
}

var EnumValuesAny = map[string]Any{
	"NONE":      AnyNONE,
	"FindNode":  AnyFindNode,
	"FindValue": AnyFindValue,
	"Store":     AnyStore,
}

func (v Any) String() string {
	if s, ok := EnumNamesAny[v]; ok {
		return s
	}
	return "Any(" + strconv.FormatInt(int64(v), 10) + ")"
}
