// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type EventType int8

const (
	EventTypePING       EventType = 0
	EventTypePONG       EventType = 1
	EventTypeSTORE      EventType = 2
	EventTypeFIND_NODE  EventType = 3
	EventTypeFIND_VALUE EventType = 4
)

var EnumNamesEventType = map[EventType]string{
	EventTypePING:       "PING",
	EventTypePONG:       "PONG",
	EventTypeSTORE:      "STORE",
	EventTypeFIND_NODE:  "FIND_NODE",
	EventTypeFIND_VALUE: "FIND_VALUE",
}

var EnumValuesEventType = map[string]EventType{
	"PING":       EventTypePING,
	"PONG":       EventTypePONG,
	"STORE":      EventTypeSTORE,
	"FIND_NODE":  EventTypeFIND_NODE,
	"FIND_VALUE": EventTypeFIND_VALUE,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
