name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.18

    steps:
      - uses: actions/checkout@v2

      - name: Test package
        run: go test -v -race ./...
